title: Supreme Court Practice Directions 2021
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-supreme-court-practice-directions-2021
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
offline: false
google_analytics: UA-113717369-6

styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'Supreme Court Practice Directions 2021'
    subtitle: ''
    order:
      - 'PART-01-Introduction.md'
      - 'PART-02-Registry, Administration and Finance.md'
      - 'PART-03-Electronic Filing and Service.md'
      - 'PART-04-Electronic Filing and Service for Criminal Proceedings.md'
      - 'PART-05-Civil Proceedings that Do Not Use the Electronic Filing Service.md'
      - 'PART-06-Amicable Resolution of Disputes for Civil Cases.md'
      - 'PART-07-Case Conferences.md'
      - 'PART-08-Originating Processes, Documents, and Service In or Out of Singapore.md'
      - 'PART-09-Interlocutory Applications.md'
      - 'PART-10-Evidence – Witnesses, Affidavits and Exhibits.md'
      - 'PART-11-Conduct of Court Proceedings.md'
      - 'PART-12-Judgments and Orders.md'
      - 'PART-13-Civil Appeals before the General Division.md'
      - 'PART-14-Proceedings before the Appellate Division, the Court of Appeal, the Court of 3 Supreme Court Judges under the Legal Profession Act and appeals to the General Division under the Medical Registration Act.md'
      - 'PART-15-Assessment of Costs Matters and Costs.md'
      - 'PART-16-Enforcement of Judgments and Orders.md'
      - 'PART-17-Admiralty Matters.md'
      - 'PART-18-Matters Under The Legal Profession Act.md'
      - 'PART-19-Bankruptcy and Winding Up Matters.md'
      - 'PART-20-Medical Negligence Claims.md'
      - 'PART-21-Reference to Actuarial Tables in Personal Injury and Death Claims.md'
      - 'PART-22-Other Matters Specific to Criminal Proceedings.md'
      - 'Appendices.md'
